### ISSUE TITLE
Use constants captured in a namespace instead of #defines

### ISSUE THREAD

**Issue by PiJoules** [jmal0/sudoku#3]
namespace definitions {
    const int SUDOKU_SIZE = 0;
}

as opposed to
# define SUDOKU_SIZE 9

**Comment by jmal0** [comment]
That would be more verbose and typing is hard for me

**Comment by PiJoules** [comment]
This would be less messy. Get better at typing.

**Comment by jmal0** [comment]
I don't need a namespace
