### ISSUE TITLE
Mixed usage of printf and std::cout

### ISSUE THREAD

**Issue by PiJoules** [jmal0/sudoku#6]
void Sudoku::print() const{
    for (int r = 0; r < SUDOKU_SIZE; ++r){
        for (int c = 0; c < SUDOKU_SIZE; ++c){
           printf("%c ", grid[PUZZ_IND(r,c)] + '0');
        }
        std::cout << std::endl;
    }
}

**Comment by jmal0** [comment]
cout wasn't working for me because I am not smart

**Comment by jmal0** [comment]
the second half of that was an oversight on my part

**Comment by PiJoules** [comment]
Maybe

static inline char intToChar(int i){
    return i + '0';
}

std::cout << intToChar(grid[PUZZ_IND(r,c)]) << std::endl;

**Comment by jmal0** [comment]
I like printf better

**Comment by PiJoules** [comment]
This isn't c.

**Comment by jmal0** [comment]
printf is faster

**Comment by PiJoules** [comment]
Where is your source for this?

**Comment by jmal0** [comment]
http://stackoverflow.com/a/2873251 just one of many discussions

**Comment by PiJoules** [comment]
M'kay, I see that printf is faster, but look at the other responses, especially "Differences nobody cares about" and the top response.

**Comment by jmal0** [comment]
i care tho

**Comment by PiJoules** [comment]
No you don't

**Comment by jmal0** [comment]
you can't tell me how to feel

**Comment by PiJoules** [comment]
I can't, but consistent c++ coding conventions can.
