### ISSUE TITLE
Using references instead of pointers

### ISSUE THREAD

**Issue by PiJoules** [jmal0/sudoku#7]
Sudoku\* puzz = SudokuIO::readSudokuFile(&file);
...
delete puzz;

If you used references, or even add a constructor for Sudoku that takes an fstream, would not have to worry about deleting puzz afterwards.

**Comment by jmal0** [comment]
I thought it would go out of scope and get deleted

**Comment by PiJoules** [comment]
Because you used new in readSudokuFile, you have to manually delete evry tim. Using a reference (Sudoku& puzz) will have it removed from the stack once leaving scope.
