### ISSUE TITLE
Hardcoded values in sudokuIO.cpp

### ISSUE THREAD

**Issue by PiJoules** [jmal0/sudoku#8]

**Comment by jmal0** [comment]
oops I'll add a #define NINE '9' and #define ZERO '0' and then I'll have perfect code

**Comment by PiJoules** [comment]
Convetion would actually be more along the lines of

static const char MIN_CHAR = '0';
static const char MAX_CHAR = '9';

**Comment by PiJoules** [comment]
Maybe also a static inline function for converting a char to int.
