### ISSUE TITLE
Single project header

### ISSUE THREAD

**Issue by PiJoules** [jmal0/sudoku#9]
It may be simpler to just have one header that imports
# include "../include/sudoku_definitions.h"
# include "../include/Sudoku.h"
# include "../include/SudokuIO.h"

so you would only have to include this one header instead of all 3 whenever you need them.

**Comment by jmal0** [comment]
More of a suggestion than an issue

**Comment by PiJoules** [comment]
Cleaner code. If you need to add another header, you would only have to add it in one extra place as opposed to all source files that use these headers.

**Comment by jmal0** [comment]
I like to be explicit about what I need included

**Comment by PiJoules** [comment]
You will be more explicit since with one header, you're saying "If you want to use this code, you MUST include this ONE header."
